export const siteConfig = {
  name: "Isaac Laurent | Developer Portfolio Template",
  authorName: "Isaac Laurent",
  username: "IsaacLaurent",
  description:
    "Isaac Laurent's portfolio - A modern, responsive Next.js portfolio for developers. This open-source template can be customized to showcase your own skills, projects, and professional experience.",
  url: "https://isaaclaurent.xyz",
  links: {
    github: "https://github.com/LRenzo0801",
  },
  ogImage: "https://isaaclaurent.xyz/isaac-img.jpg",
  iconIco:
    "https://res.cloudinary.com/dbfvcn3f6/image/upload/v1692357384/assets/isaac-favicon.ico",
  logoIcon:
    "https://res.cloudinary.com/dbfvcn3f6/image/upload/v1692357294/assets/isaac-logo.png",
  keywords: [
    "Isaac Laurent",
    "Full Stack Blockchain Engineer",
    "Web Developer Portfolio",
    "Next.js portfolio template",
    "React portfolio template",
    "Developer portfolio template",
    "Portfolio website template",
    "Next.js template",
    "Modern portfolio website",
    "Frontend developer portfolio",
    "Full Stack Blockchain Engineer portfolio",
    "Open source portfolio template",
    "Web developer portfolio template",
    "Responsive portfolio template",
    "React.js portfolio",
    "Tailwind CSS portfolio",
    "Developer showcase template",
    "Free portfolio template",
    "Next.js 13 template",
    "Shadcn UI template",
    "Career timeline template",
    "Portfolio with dark mode",
    "GitHub portfolio template",
  ],
};
